@startuml sample

package "etrobocon2024" {
    package "module" {
        package "API" {
            class Controller{
                + static constexpr double MOTOR_PWM_MAX = 100.0
                + static constexpr double MOTOR_PWM_MIN = -100.0
                + Controller(rightWheel(PORT_B), leftWheel(PORT_C), armMortor(PORT_A))
                + void setRightMotorPwm(const double)
                + void setLeftMotorPwm(const double)
                + void resetRightMotorPwm()
                + void resetLeftMotorPwm()
                + void resetWheelsMotorPwm()
                + void stopWheelsMotor()
                + void setArmMotorPwm(const double)
                + void resetArmMotorPwm()
                + void stopArmMotor()
                + double getRightMotorPwm()
                + double getLeftMotorPwm()
                - ev3api::Motor rightWheel
                - ev3api::Motor leftWheel
                - ev3api::Motor armMotor
                - static double pwmOfRightWheel
                - static double pwmOfLeftWheel
                - static double pwmOfArm
                - double limitPwmValue(const double)
            }
            class Measurer {
                + Measurer()
                + int getBrightness()
                + rgb_raw_t getRawColor()
                + int getLeftCount()
                + int getRightCount()
                + int getArmMotorCount()
                + bool getLeftButton()
                + bool getRightButton()
                + bool getEnterButton()
                + int getForwardDistance()
                + double getVoltage()
                - ev3api::ColorSensor colorSensor
                - ev3api::SonarSensor sonarSensor
                - ev3api::Motor leftWheel
                - ev3api::Motor rightWheel
                - ev3api::Motor armMotor
            }
            class Timer {
                + Timer()
                + void sleep(int)
                + int now()
                - ev3api::Clock clock
            }
        }

        package "Calculator" {
            enum COLOR <<int>> {
                NONE = 0
                BLACK = 1
                WHITE = 2
                BLUE = 3
                GREEN = 4
                YELLOW = 5
                RED = 6
            }

            struct Hsv
            class ColorJudge
            class Mileage
            struct PidGain
            class Pid
            class SpeedCalculator
        }

        package "common" {
            class Logger
            class StringOperator
        }

        package "Motion" {
            class ColorLineTracing
            LineTracing <|-- ColorLineTracing

            class ColorStraight
            Straight <|-- ColorStraight

            class DistanceLineTraicing
            LineTracing <|-- DistanceLineTraicing

            class DistanceStraight
            Straight <|-- DistanceStraight

            class EdgeChanging
            Motion <|-- EdgeChanging

            class LineTracing
            Motion <|-- LineTracing

            class Motion

            class PwmRotation
            Rotation <|-- PwmRotation

            class Rotation
            Motion <|-- Rotation

            class Sleeping
            Motion <|-- Sleeping

            class Straight
            Motion <|-- Straight
        }

        enum Area
        class AreaMaster

        class Calibrator

        class EtRobocon2024

        enum COMMAND

        class MotionParser
    }
}

package "etrobocon2024-camera-system" {
    package "src" {
        class CameraSystem
        class Client
        class DetectObject
        class ImageProcessing
        class ResponseError
        class OfficialInterface
        class RoboSnap
        class TrainTracker
    }
}
@enduml
